import { useState, useEffect } from 'react';
import { api } from '../api';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Textarea } from './ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Badge } from './ui/badge';
import { Plus, Trash2, FileText, Package, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';

interface PRItem {
  id: number;
  itemDescription: string;
  quantity: string;
  unit: string;
  estimatedCost: string;
}

interface RecentPRItem {
  id: number;
  itemDescription: string;
  quantity: number;
  unit: string;
  estimatedCost: number;
}

interface RecentPR {
  id: number;
  prNumber: string;
  department: string;
  requestedBy: number;
  description: string;
  status: string;
  approvedBy: string;
  approvedOn: string;
  budgetHead: string;
  createdAt: string;
  items: RecentPRItem[];
}

interface PurchaseRequisitionProps {
  authToken?: string;
  userId?: number;
  userEmail?: string;
}

export function PurchaseRequisition({ authToken, userId, userEmail }: PurchaseRequisitionProps) {
  const [items, setItems] = useState<PRItem[]>([
    { id: 1, itemDescription: '', quantity: '', unit: '', estimatedCost: '' }
  ]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [recentPRs, setRecentPRs] = useState<RecentPR[]>([]);
  const [isLoadingRecent, setIsLoadingRecent] = useState(false);

  // Extract numeric user ID from token if userId is not a number
  const getNumericUserId = (): number | null => {
    if (userId && typeof userId === 'number') {
      return userId;
    }

    // If userId is not valid, try to extract from token
    if (authToken) {
      try {
        const tokenPayload = JSON.parse(atob(authToken.split('.')[1]));
        console.log('Token Payload in PR:', tokenPayload);
        return tokenPayload.id || null;
      } catch (error) {
        console.error('Error parsing token:', error);
        return null;
      }
    }

    return null;
  };

  const numericUserId = getNumericUserId();

  const addItem = () => {
    setItems([...items, {
      id: items.length + 1,
      itemDescription: '',
      quantity: '',
      unit: '',
      estimatedCost: ''
    }]);
  };

  const removeItem = (id: number) => {
    if (items.length > 1) {
      setItems(items.filter(item => item.id !== id));
    } else {
      toast.error('Cannot remove last item', {
        description: 'PR must have at least one item'
      });
    }
  };

  const updateItem = (id: number, field: keyof PRItem, value: string) => {
    setItems(items.map(item =>
      item.id === id ? { ...item, [field]: value } : item
    ));
  };

  // Fetch recent PRs created by the user
  const fetchRecentPRs = async () => {
    if (!authToken || !numericUserId) return;

    setIsLoadingRecent(true);
    try {
      const response = await api.get(`/procurement/pr/by-created?createdById=${numericUserId}&page=0&pageSize=5`, {
        headers: {
          'accept': '*/*'
        }
      });

      if (response.ok) {
        const data = await response.json();
        setRecentPRs(data.content || []);
      } else {
        console.error('Failed to fetch recent PRs');
      }
    } catch (error) {
      console.error('Error fetching recent PRs:', error);
    } finally {
      setIsLoadingRecent(false);
    }
  };

  // Load recent PRs on component mount
  useEffect(() => {
    fetchRecentPRs();
  }, [authToken, numericUserId]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const formData = new FormData(e.currentTarget as HTMLFormElement);

    // Validate that all items have required fields
    const hasEmptyItems = items.some(item =>
      !item.itemDescription.trim() ||
      !item.quantity ||
      !item.unit ||
      !item.estimatedCost
    );

    if (hasEmptyItems) {
      toast.error('Incomplete item details', {
        description: 'Please fill in all item fields'
      });
      return;
    }

    // Prepare items array according to new API structure
    const prItems = items.map(item => ({
      itemDescription: item.itemDescription,
      quantity: parseFloat(item.quantity),
      unit: item.unit,
      estimatedCost: parseFloat(item.estimatedCost)
    }));

    // Prepare the PR data according to new API structure
    const prData = {
      prNumber: '', // Will be auto-generated by backend
      department: formData.get('department') as string,
      requestedBy: numericUserId || null, // Use numeric user ID from token
      description: formData.get('description') as string,
      status: 'RAISED',
      budgetHead: formData.get('budgetHead') as string,
      approvedBy: '', // Will be set during approval
      approvedOn: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      items: prItems
    };

    console.log('Submitting PR:', prData);

    // If authToken is available, call the API
    if (authToken) {
      await submitToAPI(prData);
    } else {
      // Fallback to mock submission
      toast.success('Purchase Requisition submitted successfully!', {
        description: 'PR has been created and sent for approval.'
      });
      resetForm();
    }
  };

  const submitToAPI = async (prData: any) => {
    setIsSubmitting(true);
    try {
      const response = await api.post('/procurement/pr', prData, {
        headers: {
          'accept': '*/*',
          'Content-Type': 'application/json'
        }
      });

      if (response.ok) {
        const result = await response.json();
        console.log('PR created successfully:', result);
        toast.success('Purchase Requisition submitted successfully!', {
          description: `${result.prNumber || 'PR'} has been created with ${items.length} item(s) and sent for approval.`
        });

        resetForm();
      } else {
        const errorText = await response.text();
        console.error('API Error:', errorText);
        toast.error('Failed to submit PR', {
          description: errorText || 'Please try again later.'
        });
      }
    } catch (error) {
      console.error('Error submitting PR:', error);
      toast.error('Error submitting PR', {
        description: 'Network error. Please check your connection and try again.'
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  const resetForm = () => {
    // Reset form
    const form = document.querySelector('form') as HTMLFormElement;
    if (form) form.reset();

    // Reset items to initial state
    setItems([{ id: 1, itemDescription: '', quantity: '', unit: '', estimatedCost: '' }]);

    // Refresh recent PRs list
    fetchRecentPRs();
  };

  const calculateTotalCost = () => {
    return items.reduce((total, item) => {
      const cost = parseFloat(item.estimatedCost) || 0;
      return total + cost;
    }, 0);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="size-5 text-blue-600" />
            New Purchase Requisition
          </CardTitle>
          <CardDescription>
            Submit a new procurement request for materials or services
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-6">
            {/* Basic Information */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="department">Department / Initiated By *</Label>
                <Select name="department" required>
                  <SelectTrigger id="department">
                    <SelectValue placeholder="Select department" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Facility Management">Facility Management</SelectItem>
                    <SelectItem value="Estate Management">Estate Management</SelectItem>
                    <SelectItem value="Security">Security</SelectItem>
                    <SelectItem value="Housekeeping">Housekeeping</SelectItem>
                    <SelectItem value="Administration">Administration</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="budgetHead">Budget Head *</Label>
                <Select name="budgetHead" required>
                  <SelectTrigger id="budgetHead">
                    <SelectValue placeholder="Select budget head" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Maintenance">Maintenance</SelectItem>
                    <SelectItem value="Corpus">Corpus</SelectItem>
                    <SelectItem value="Capex">Capital Expenditure (Capex)</SelectItem>
                    <SelectItem value="Operational">Operational</SelectItem>
                    <SelectItem value="Miscellaneous">Miscellaneous</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            {/* PR Description */}
            <div className="space-y-2">
              <Label htmlFor="description">PR Description / Purpose *</Label>
              <Textarea
                id="description"
                name="description"
                placeholder="Brief overview of this purchase requisition (e.g., 'Monthly STP maintenance supplies')"
                rows={3}
                required
              />
            </div>

            {/* Items Section */}
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <Label className="flex items-center gap-2">
                  <Package className="size-4 text-blue-600" />
                  Items / Services Details
                </Label>
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={addItem}
                  disabled={isSubmitting}
                >
                  <Plus className="size-4 mr-1" />
                  Add Item
                </Button>
              </div>

              {items.map((item, index) => (
                <div key={item.id} className="p-4 border border-slate-200 rounded-lg space-y-4 bg-slate-50">
                  <div className="flex items-center justify-between">
                    <h4 className="text-sm text-slate-900">Item {index + 1}</h4>
                    {items.length > 1 && (
                      <Button
                        type="button"
                        variant="ghost"
                        size="sm"
                        onClick={() => removeItem(item.id)}
                        disabled={isSubmitting}
                      >
                        <Trash2 className="size-4 text-red-600" />
                      </Button>
                    )}
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor={`itemDescription-${item.id}`}>
                      Item / Service Description *
                    </Label>
                    <Textarea
                      id={`itemDescription-${item.id}`}
                      value={item.itemDescription}
                      onChange={(e) => updateItem(item.id, 'itemDescription', e.target.value)}
                      placeholder="e.g., Chlorine tablets for water treatment"
                      rows={2}
                      required
                      disabled={isSubmitting}
                    />
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor={`quantity-${item.id}`}>Quantity *</Label>
                      <Input
                        id={`quantity-${item.id}`}
                        type="number"
                        step="0.01"
                        value={item.quantity}
                        onChange={(e) => updateItem(item.id, 'quantity', e.target.value)}
                        placeholder="e.g., 50"
                        required
                        disabled={isSubmitting}
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor={`unit-${item.id}`}>Unit *</Label>
                      <Select
                        value={item.unit}
                        onValueChange={(value) => updateItem(item.id, 'unit', value)}
                        required
                        disabled={isSubmitting}
                      >
                        <SelectTrigger id={`unit-${item.id}`}>
                          <SelectValue placeholder="Select unit" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="kg">Kilograms (kg)</SelectItem>
                          <SelectItem value="litre">Litres</SelectItem>
                          <SelectItem value="piece">Pieces</SelectItem>
                          <SelectItem value="box">Boxes</SelectItem>
                          <SelectItem value="set">Sets</SelectItem>
                          <SelectItem value="meter">Meters</SelectItem>
                          <SelectItem value="sqft">Square Feet</SelectItem>
                          <SelectItem value="service">Service (AMC/Work)</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor={`estimatedCost-${item.id}`}>
                        Estimated Cost (₹) *
                      </Label>
                      <Input
                        id={`estimatedCost-${item.id}`}
                        type="number"
                        step="0.01"
                        value={item.estimatedCost}
                        onChange={(e) => updateItem(item.id, 'estimatedCost', e.target.value)}
                        placeholder="e.g., 15000"
                        required
                        disabled={isSubmitting}
                      />
                    </div>
                  </div>
                </div>
              ))}

              {/* Total Cost Summary */}
              <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
                <div className="flex items-center justify-between">
                  <span className="text-slate-900">Total Estimated Cost:</span>
                  <span className="text-blue-900">
                    ₹{calculateTotalCost().toLocaleString('en-IN', {
                      minimumFractionDigits: 2,
                      maximumFractionDigits: 2
                    })}
                  </span>
                </div>
                <p className="text-xs text-slate-600 mt-2">
                  {items.length} item(s) in this requisition
                </p>
              </div>
            </div>

            {/* Submit Actions */}
            <div className="flex gap-3 pt-4 border-t">
              <Button
                type="submit"
                className="flex-1 md:flex-initial"
                disabled={isSubmitting}
              >
                {isSubmitting ? 'Submitting...' : 'Submit for Approval'}
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={resetForm}
                disabled={isSubmitting}
              >
                Clear Form
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>

      {/* Recent PRs */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Your Recent Requisitions</CardTitle>
              <CardDescription>Track status of your submitted PRs</CardDescription>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={fetchRecentPRs}
              disabled={isLoadingRecent}
            >
              <RefreshCw className={`h-4 w-4 ${isLoadingRecent ? 'animate-spin' : ''}`} />
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {isLoadingRecent ? (
            <div className="flex items-center justify-center py-8">
              <RefreshCw className="h-6 w-6 animate-spin text-slate-400" />
            </div>
          ) : recentPRs.length === 0 ? (
            <div className="text-center py-8 text-slate-500">
              <FileText className="h-12 w-12 mx-auto mb-2 text-slate-300" />
              <p>No requisitions yet</p>
              <p className="text-sm">Your submitted PRs will appear here</p>
            </div>
          ) : (
            <div className="space-y-3">
              {recentPRs.map((pr) => (
                <div key={pr.id} className="flex items-center justify-between p-3 border border-slate-200 rounded-lg">
                  <div>
                    <p className="text-slate-900">{pr.prNumber}</p>
                    <p className="text-sm text-slate-600">
                      {pr.description} ({pr.items.length} item{pr.items.length !== 1 ? 's' : ''})
                    </p>
                    <p className="text-xs text-slate-500 mt-1">{pr.department} • {pr.budgetHead}</p>
                  </div>
                  <div className="text-right">
                    <Badge
                      variant={
                        pr.status === 'APPROVED' ? 'default' :
                          pr.status === 'RAISED' ? 'outline' :
                            'secondary'
                      }
                    >
                      {pr.status}
                    </Badge>
                    <p className="text-xs text-slate-500 mt-1">
                      {new Date(pr.createdAt).toLocaleDateString('en-GB', {
                        day: '2-digit',
                        month: 'short',
                        year: 'numeric'
                      })}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
